### ISSUE TITLE
ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway"

### ISSUE THREAD

**Issue by AsdertyTreds** [orenlab/pytmbot#26]
2024-05-14 01:15:09,697 (__init__.py:1212 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway"
2024-05-14 01:15:09,702 (__init__.py:1214 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 1205, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 675, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 647, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 327, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 167, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 194, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway
"
2024-05-14 01:15:10,083 (__init__.py:1212 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway"
2024-05-14 01:15:10,085 (__init__.py:1214 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 1205, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 675, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 647, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 327, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 167, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 194, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway
"
2024-05-14 01:15:10,714 (__init__.py:1212 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway"
2024-05-14 01:15:10,716 (__init__.py:1214 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 1205, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 675, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 647, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 327, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 167, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 194, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway
"
2024-05-14 01:16:16 - pyTMbot - ERROR - Connection error. Retry after 30 seconds [main.py | start_polling:44]
2024-05-14 01:16:46 - pyTMbot - INFO - Start polling [main.py | start_polling:39]

**Comment by AsdertyTreds** [comment]
there were no problems connecting to the Internet

**Comment by orenlab** [comment]
Hi, @AsdertyTreds!

Can you please try the latest version from the main branch and let me know the outcome?

I have been testing this all day and, according to my logs, everything seems to be working fine.

The only thing to note is that I am not sure which version you currently have. I have transferred all the relevant configuration information to `.pytmbotenv`. If you experience any issues during startup, could you please try running setup_bot.py again?

**Comment by orenlab** [comment]
Well, I have added a custom exception handler. Let's focus on the branch [26-error-telebot-threaded-polling-exception](https://github.com/orenlab/pytmbot/tree/26-error-telebot-threaded-polling-exception)

**Comment by orenlab** [comment]
@AsdertyTreds 

I will be making some additions to branch #26 and am currently testing this solution, which is recommended by the developers of PyTelegramBotAPI for exception handling. 

I will let you know about my decision.

**Comment by AsdertyTreds** [comment]
2024-05-16 01:10:59,244 (__init__.py:1221 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway"
2024-05-16 01:10:59,245 (__init__.py:1223 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway
"
2024-05-16 01:10:59,623 (__init__.py:1221 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway"
2024-05-16 01:10:59,626 (__init__.py:1223 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway
"
2024-05-16 01:11:00,255 (__init__.py:1221 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway"
2024-05-16 01:11:00,257 (__init__.py:1223 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway
"
2024-05-16 01:11:01,386 (__init__.py:1221 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway"
2024-05-16 01:11:01,388 (__init__.py:1223 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/venv/lib/python3.12/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway
"
2024-05-16 01:12:08 - pyTMbot - ERROR - Connection error. Retry after 5 seconds [main.py | start_polling:44]
2024-05-16 01:12:13 - pyTMbot - INFO - Start polling [main.py | start_polling:39]

**Comment by orenlab** [comment]
I confirm that there were also exceptions at night. I will consider this

**Comment by orenlab** [comment]
@AsdertyTreds,

Solved the problem of catching exceptions from Telebot. Updates are available in the branch [26-error-telebot-threaded-polling-exception](https://github.com/orenlab/pytmbot/tree/26-error-telebot-threaded-polling-exception). The tests have shown that everything is working correctly. Today, I will be transferring these changes to the development branch.
