### ISSUE TITLE
ValueError: time data does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

### ISSUE THREAD

**Issue by orenlab** [orenlab/pytmbot#63]
**Describe the bug**
In v.0.2.1:

```bash
pytmbot  | 2024-12-12 [17:57:49][ERROR   ][logs            ] › Error in inline session @handle_image_updates for user: *********_bot, exception: Error during template compilation 
pytmbot  | Traceback (most recent call last):
pytmbot  | 
pytmbot  |   File "/opt/app/pytmbot/parsers/filters.py", line 16, in format_timestamp
pytmbot  |     dt = datetime.strptime(value, "%Y-%m-%dT%H:%M:%S.%fZ")
pytmbot  |          │        │        └ '2024-12-12T12:47:38.540792207Z'
pytmbot  |          │        └ <method 'strptime' of 'datetime.datetime' objects>
pytmbot  |          └ <class 'datetime.datetime'>
pytmbot  | 
pytmbot  |   File "/usr/local/lib/python3.13/_strptime.py", line 676, in _strptime_datetime
pytmbot  |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
pytmbot  |                                     │         │            └ '%Y-%m-%dT%H:%M:%S.%fZ'
pytmbot  |                                     │         └ '2024-12-12T12:47:38.540792207Z'
pytmbot  |                                     └ <function _strptime at 0x77c1cfb84a40>
pytmbot  |   File "/usr/local/lib/python3.13/_strptime.py", line 455, in _strptime
pytmbot  |     raise ValueError("time data %r does not match format %r" %
pytmbot  | 
pytmbot  | ValueError: time data '2024-12-12T12:47:38.540792207Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

**Comment by orenlab** [comment]
Fix in a2255c0d03eb27da8d0948536e43c11ed32f6c0e
